image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - deploy

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:latest

deploy-job:
  stage: deploy
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    - tags